# .travis.yml
language: csharp
dist: xenial
dotnet: 2.2.103
mono: none

solution: WeatherApi.sln

script:
- cd Server
- dotnet restore
- dotnet build
- dotnet test WeatherApi.Tests/WeatherApi.Tests.csproj